using Checkout;
using Checkout.Common;
using Checkout.Payments.Request;
using Checkout.Payments.Request.Source;
using Checkout.Payments.Response;
using Environment = System.Environment;

ICheckoutApi api = CheckoutSdk.Builder().StaticKeys()
    .SecretKey(Environment.GetEnvironmentVariable("sk_sbox_XXX"))
    .Build();

// The token generated by Frames on the client side
PaymentRequest paymentRequest = new PaymentRequest
{
    Source = new RequestTokenSource
    {
        Token = "tok_XXX"
    },
    Currency = Currency.GBP,
    Amount = 2499,
    ProcessingChannelId = "pc_XXX"
};

try
{
    PaymentResponse paymentResponse = await api.PaymentsClient().RequestPayment(paymentRequest);
    Console.WriteLine("Success, here is your payment status = " + paymentResponse.Status);
}
catch (CheckoutApiException ex)
{
    Console.WriteLine("Error details: " + ex.ErrorDetails["error_codes"]);
}