const { Checkout } = require('checkout-sdk-node');

const cko = new Checkout('sk_sbox_XXX');

router.post('/pay', async (req, res) => {

    // The token generated by Frames on the client side
    const myToken = req.body.token;

    const paymentResponse = await cko.payments.request({
        source: {
            token: myToken,
        },
        currency: 'GBP',
        processing_channel_id: 'pc_XXX',
        amount: 2499,
    });

    res.send(paymentResponse);
});