import os

from checkout_sdk import CheckoutSdk
from checkout_sdk.common.enums import Currency
from checkout_sdk.exception import CheckoutApiException
from checkout_sdk.payments.payments import PaymentRequest, PaymentRequestTokenSource

api = CheckoutSdk().builder().secret_key(os.environ.get('sk_sbox_XXX')).build()

# The token generated by Frames on the client side
payment_request = PaymentRequest()
payment_request.source = PaymentRequestTokenSource()
payment_request.source.token = 'tok_XXX'
payment_request.currency = Currency.GBP
payment_request.processing_channel_id = 'pc_XXX'
payment_request.amount = 2499

try:
    payment_response = api.payments.request_payment(payment_request)
    print(f"Success, here is your payment status = {payment_response.status} ")
except CheckoutApiException as err:
    print(f"Error Details = {err.error_details}")